import type { DividendEtf } from '../types/dividend';

/**
 * 배당수익률·성장률은 2026년 상반기 기준 검색으로 확인한 근사값이며,
 * 계산기 안에서 사용자가 직접 수정할 수 있는 기본값(default)일 뿐이다.
 */
export const DIVIDEND_ETFS: DividendEtf[] = [
  // 미국 상장 ETF
  {
    ticker: 'SCHD',
    name: 'Schwab US Dividend Equity ETF',
    region: 'US',
    currency: 'USD',
    category: '배당성장',
    payoutFrequency: 'quarterly',
    defaultYield: 0.038,
    defaultGrowthRate: 0.06,
    accent: '#378add',
  },
  {
    ticker: 'VYM',
    name: 'Vanguard High Dividend Yield ETF',
    region: 'US',
    currency: 'USD',
    category: '고배당',
    payoutFrequency: 'quarterly',
    defaultYield: 0.029,
    defaultGrowthRate: 0.05,
    accent: '#0ea5e9',
  },
  {
    ticker: 'VIG',
    name: 'Vanguard Dividend Appreciation ETF',
    region: 'US',
    currency: 'USD',
    category: '배당성장',
    payoutFrequency: 'quarterly',
    defaultYield: 0.017,
    defaultGrowthRate: 0.08,
    accent: '#6366f1',
  },
  {
    ticker: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    region: 'US',
    currency: 'USD',
    category: '지수추종',
    payoutFrequency: 'quarterly',
    defaultYield: 0.012,
    defaultGrowthRate: 0.09,
    accent: '#2563eb',
  },
  {
    ticker: 'DGRO',
    name: 'iShares Core Dividend Growth ETF',
    region: 'US',
    currency: 'USD',
    category: '배당성장',
    payoutFrequency: 'quarterly',
    defaultYield: 0.02,
    defaultGrowthRate: 0.07,
    accent: '#14b8a6',
  },
  {
    ticker: 'HDV',
    name: 'iShares Core High Dividend ETF',
    region: 'US',
    currency: 'USD',
    category: '고배당',
    payoutFrequency: 'quarterly',
    defaultYield: 0.035,
    defaultGrowthRate: 0.04,
    accent: '#84cc16',
  },
  {
    ticker: 'SPYD',
    name: 'SPDR Portfolio S&P 500 High Dividend ETF',
    region: 'US',
    currency: 'USD',
    category: '고배당',
    payoutFrequency: 'quarterly',
    defaultYield: 0.043,
    defaultGrowthRate: 0.03,
    accent: '#a855f7',
  },
  {
    ticker: 'DIVO',
    name: 'Amplify CWP Enhanced Dividend Income ETF',
    region: 'US',
    currency: 'USD',
    category: '커버드콜',
    payoutFrequency: 'monthly',
    defaultYield: 0.047,
    defaultGrowthRate: 0.05,
    accent: '#f59e0b',
  },
  {
    ticker: 'JEPI',
    name: 'JPMorgan Equity Premium Income ETF',
    region: 'US',
    currency: 'USD',
    category: '커버드콜',
    payoutFrequency: 'monthly',
    defaultYield: 0.08,
    defaultGrowthRate: 0.02,
    accent: '#d85a30',
  },
  {
    ticker: 'JEPQ',
    name: 'JPMorgan Nasdaq Equity Premium Income ETF',
    region: 'US',
    currency: 'USD',
    category: '커버드콜',
    payoutFrequency: 'monthly',
    defaultYield: 0.11,
    defaultGrowthRate: 0.01,
    accent: '#ef4444',
  },

  // 국내 상장 ETF
  {
    ticker: 'TIGER 미국배당다우존스',
    name: 'TIGER 미국배당다우존스 (458730)',
    region: 'KR',
    currency: 'KRW',
    category: '배당성장 (SCHD 추종)',
    payoutFrequency: 'quarterly',
    defaultYield: 0.036,
    defaultGrowthRate: 0.06,
    accent: '#f97316',
  },
  {
    ticker: 'SOL 미국배당다우존스',
    name: 'SOL 미국배당다우존스(월배당) (446720)',
    region: 'KR',
    currency: 'KRW',
    category: '배당성장 (SCHD 추종·월배당)',
    payoutFrequency: 'monthly',
    defaultYield: 0.033,
    defaultGrowthRate: 0.06,
    accent: '#06b6d4',
  },
  {
    ticker: 'ACE 미국배당다우존스',
    name: 'ACE 미국배당다우존스 (402970)',
    region: 'KR',
    currency: 'KRW',
    category: '배당성장 (SCHD 추종)',
    payoutFrequency: 'quarterly',
    defaultYield: 0.036,
    defaultGrowthRate: 0.06,
    accent: '#d946ef',
  },
  {
    ticker: 'TIGER 배당성장',
    name: 'TIGER 배당성장 (211560)',
    region: 'KR',
    currency: 'KRW',
    category: '국내 배당성장',
    payoutFrequency: 'quarterly',
    defaultYield: 0.025,
    defaultGrowthRate: 0.05,
    accent: '#65a30d',
  },
  {
    ticker: 'KODEX 배당가치',
    name: 'KODEX 배당가치',
    region: 'KR',
    currency: 'KRW',
    category: '국내 배당가치',
    payoutFrequency: 'quarterly',
    defaultYield: 0.03,
    defaultGrowthRate: 0.04,
    accent: '#ec4899',
  },
  {
    ticker: 'ARIRANG 고배당주',
    name: 'ARIRANG 고배당주',
    region: 'KR',
    currency: 'KRW',
    category: '국내 고배당',
    payoutFrequency: 'quarterly',
    defaultYield: 0.045,
    defaultGrowthRate: 0.02,
    accent: '#8b5cf6',
  },
  {
    ticker: 'KODEX 미국배당프리미엄액티브',
    name: 'KODEX 미국배당프리미엄액티브(커버드콜)',
    region: 'KR',
    currency: 'KRW',
    category: '커버드콜 (월배당)',
    payoutFrequency: 'monthly',
    defaultYield: 0.1,
    defaultGrowthRate: 0.01,
    accent: '#ba7517',
  },
  {
    ticker: 'TIGER 미국나스닥100커버드콜',
    name: 'TIGER 미국나스닥100커버드콜',
    region: 'KR',
    currency: 'KRW',
    category: '커버드콜 (월배당)',
    payoutFrequency: 'monthly',
    defaultYield: 0.115,
    defaultGrowthRate: 0.005,
    accent: '#1d9e75',
  },
];
